{% raw %}apiVersion: v1
kind: Service
metadata:
  name: {{ include "{% endraw %}{{ cookiecutter.project_slug }}{% raw %}.fullname" . }}
  labels:
    {{- include "{% endraw %}{{ cookiecutter.project_slug }}{% raw %}.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "{% endraw %}{{ cookiecutter.project_slug }}{% raw %}.selectorLabels" . | nindent 4 }}
{% endraw %}